---
title: "oeHBCdiffAnalysis"
author: "Connor Bybee"
date: "December 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(FastProjectR)
library(LineagePulse)
library(slingshot)
library(clusterExperiment)
library(wordspace)
```

## Load Data

```{r ,echo=FALSE}
#load('c:/Users/Connor/Downloads/oeHBCdiff_Data/oeHBCdiff_cmmerged.Rda')
#load('c:/Users/Connor/Downloads/oeHBCdiff_Data/oeHBCdiff_lineageData.Rda')
#load('c:/Users/Connor/Downloads/oeHBCdiff_Data/oeHBCdiff_slingshot.Rda')
clustLabels <- as.data.frame(read.table('c:/Users/Connor/Downloads/oeHBCdiff_Data/oeHBCdiff_clusterLabels.txt'))
```


```{r genSigs, echo=FALSE} 
sigs <- genRandomSigs(counts, 4, 10)
write.table(x = sigs,
            file = 'c:/Users/Connor/Downloads/oeHBCdiff_Data/randSigs.txt',
            sep='\t',
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE)
sigs <- c("c:/Users/Connor/Downloads/oeHBCdiff_Data/randSigs.txt")
hk <- row.names(counts)[1:10]
fp <- FastProject(counts, sigs, hk, filters=c("novar"))
fpo <- analyze(fp)
```

```{r, echo=FALSE}
viewResults(fpo)
```


```{r load pre-computed}
counts <- read.table('c:/Users/Connor/Downloads/oeHBCdiff_Data/oeHBCdiff_countsMatrix.txt', 
                     header=TRUE,
                     row.names=1)
counts <- as.matrix(counts)
load('data/oeHBCTree.Rdata')
oeHBCdiff <- read.table('c:/Users/Connor/Downloads/p63-HBC-diff/ref/oeHBCdiff_de.txt')$V1
oeHBChk <- read.table('c:/Users/Connor/Downloads/p63-HBC-diff/ref/hklist.txt')$V1
oeNLGenes <- read.table('c:/Users/Connor/Downloads/p63-HBC-diff/ref/NL_genes.txt')$V1
oeMarkers <- read.table('c:/Users/Connor/Downloads/p63-HBC-diff/ref/oe_markers27.txt')$V1
```
##
```{r pseudotimeProjection, echo=FALSE} 
root = 'OEP01_N707_S504'
#hdTree <- applySimplePPT(counts) #Run simplePPT on normalized counts
p <- TreeProjection(name = "PPT", pData = round(exp(counts)),
                    vData = round(exp(hdTree$princPnts)), adjMat = hdTree$adjMat)
pt <- pseudotimeProjection(p, root)
```

```{r}
lsObjLP <- testProjectionLineages(p, root)
lsObjLP <- testPathLineages(p, pt[1:5], root)
lsSigGenes <- testSigGenes(lsObjLP)
path <- pt$`path 9_10_19_8_20_4_2_11_18_15`
idx <-colnames(counts) %in% path$data$cell
objLP <- runLineagePulse(round(exp(counts[,idx])), dfAnnotation = path$data)
gplotCellDensity <- plotCellDensity(objLP = objLP)
print(gplotCellDensity)
gplotExprProfile <- plotGene(
    objLP = objLP, boolLogPlot = FALSE,
    strGeneID = 'Prim2',
    boolLineageContour = FALSE)
print(gplotExprProfile)
```


``` {r }
load('data/objLp_path 9_10_19_8_20_4_2_11_18_7_17.Rdata')

gplotCellDensity <- plotCellDensity(objLP = objLP)
print(gplotCellDensity)
sigGenes <- row.names(objLP$dfResults)[objLP$dfResults$padj < 0.05]
topGenes <- row.names(objLP$dfResults)[order(objLP$dfResults$padj, na.last = NA)[1:100]]
test.in.results <- sum(topGenes %in% oeHBCdiff)
gplotExprProfile <- plotGene(
    objLP = objLP, boolLogPlot = FALSE,
    strGeneID = cellName,
    boolLineageContour = FALSE)
  print(gplotExprProfile)
```



```{r }
cl <- getVerts(p)
pca <- prcomp(t(counts), scale. = FALSE)
rd <- pca$x[,1:2]
rootVert <- cl[root]

lin <- getLineages(rd, cl, start.clus=rootVert)
crv <- getCurves(lin)
plot(rd, col =  cl ,pch=16, asp = 1)
lines(crv, lwd=3)
legend("topright",
       legend=1:length(unique(cl)),
       fill=c(1:length(unique(cl))),
       pch=15,
       title = 'Vertex')
pt_s <- pseudotime(crv)
```

``` {r} 
head(objLP$dfResults)
lsHeatmaps <- sortGeneTrajectories(
    vecIDs = objLP$dfResults[which(objLP$dfResults$padj < 0.01),]$gene,
    lsMuModel = lsMuModelH1(objLP),
    dirHeatmap=NULL)
print(lsHeatmaps$hmGeneSorted)
```


``` {r}
# first, extract the model fits for a given gene again
matMeanParamFit <- getFitsMean(
    lsMuModel = lsMuModelH1(objLP),
    vecGeneIDs = objLP$dfResults[which(objLP$dfResults$padj < 0.01),]$gene)
# compute log2-fold change from first to last cell on trajectory
idxFirstCell <- which.min(dfAnnotationProc(objLP)$continuous)
idxLastCell <- which.max(dfAnnotationProc(objLP)$continuous)

#"LFC first to last cell on trajectory: "
vecLFCFL <- round( (log(matMeanParamFit[, idxLastCell]) - 
                log(matMeanParamFit[, idxFirstCell])) / log(2) ,1) 
# compute log2-fold change from minimum to maximum value of expression trajectory
cat("LFC minimum to maximum expression value of model fit: ", 
    round( (log(max(vecMeanParamFit)) - 
                log(min(vecMeanParamFit))) / log(2),1) )


vecFoldChange <- round( (log(apply(matMeanParamFit, 1, max )) - 
                log(apply(matMeanParamFit, 1, min)) / log(2)),1)
```

``` {r}
#test if know genes are in signifigant trajectory genes
lsFrac <- lapply(list(oeHBCdiff, oeHBChk, oeMarkers, oeNLGenes), function(x) {
  return(sum(x %in% row.names(matMeanParamFit)) / length(x))
})


```
