---
title: "Gene Signatures"
author: "David DeTomaso and Matthew Jones"
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('BiocStyle')`"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Gene Signatures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Getting Signatures
Gene signatures are essential to the VISION pipeline, and are fairly easy to get in any number of ways:

## Downloading Signatures
A great resource for gene signatures is `MSigDB`, curated by the Broad institute. Signatures can be browsed, searched and downloaded from [here](http://software.broadinstitute.org/gsea/msigdb/) as .gmt files, then provided to VISION to be included in the analysis.


## Creating Signatures
If there is a set of proprietary genes of interest, a user-defined signature can be created in two ways:
### creating a Signature object
Once a set of genes that are up or down regulated in the process or cell type of interest are selected, creating a Signature object is relatively straightforward:
```{r create signature object, collapse=T, eval=F}
up.genes <- c("ug1","ug2","ug3","ug4","ug5","ug6","ug7","ug8","ug9")
down.genes <- c("dg1","dg2","dg3","dg4","dg5","dg6")

sigData <- c(rep(1.0,length(up.genes)),rep(-1.0,length(down.genes)))
names(sigData) <- c(up.genes, down.genes)

sig <- createGeneSignature(name = "Interesting Process", sigData = sigData)
```

### Signature files
Signature files are supported in either a .txt or .gmt format, which are both textual formats that are easy to create.
Information on the precise acceptable format can be found [here](https://github.com/YosefLab/VISION/wiki/Signatures).

