---
title: "simulateBranchingTrajectory"
author: "Connor Bybee"
date: "November 27, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gam)
library(FastProjectR)
library(LineagePulse)
library(slingshot)
library(clusterExperiment)
library(wordspace)
#library(destiny)
source('c:/Users/Connor/FastProjectR2/cb/getVerts.R')
```

## R Markdown


load data set
```{r dataset, echo=FALSE}

scaNCellsPerEdge = 100
scaNGroups = 4
scaNCells = scaNCellsPerEdge*(scaNGroups -1)
scaNConst = 100
scaNLin = 100
scaNSigsPerGroup=5
scaNGenes = scaNConst + scaNLin + scaNGroups*scaNSigsPerGroup
lsSimulatedData <- simBranchingDataSet(
  scaNCellsPerEdge = scaNCellsPerEdge,
  scaNGroups = scaNGroups,
  scaNConst = scaNConst,
  scaNLin = scaNLin,
  scaNSigsPerGroup=scaNSigsPerGroup,
  scaMumax = 100,
  scaSDMuAmplitude = 1,
  vecNormConstExternal=NULL,
  vecDispExternal=rep(15, scaNCells),
  vecGeneWiseDropoutRates = rep(0.1, scaNGenes))

# -- read in expression data set
expr <- lsSimulatedData$counts
hkg <- lsSimulatedData$housekeeping
sigs = lsSimulatedData$sigs
write.table(x = sigs,
            file = '../data/simSigs1.txt',
            sep='\t',
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE)
sigs = c("../data/simSigs1.txt")
print(lsSimulatedData$adjMat)
```


Create FastProject Analysis

```{r fastproject, echo=FALSE}
fp <- FastProject(expr, sigs, hkg, filters=c("novar"))
fpo <- analyze(fp)
```



```{r pseudotime, echo=FALSE }
#p = fpo@filterModuleList$novar@TreeProjectionData@projections$PPT
root = 'CELL_13_1'


hdTree <- applySimplePPT(expr)
p <- TreeProjection(name = "PPT", pData = expr,
                    vData = hdTree$princPnts, adjMat = hdTree$adjMat)
pt = pseudotimeProjection(p, root)
```


```{r slingshot, echo=FALSE }
pca <- prcomp(t(log1p(expr)), scale. = FALSE)
rd <- pca$x[,1:2]
cl <- getVerts(p)

rootVert <- getRootVert(p, root)
lin <- getLineages(rd, cl, start.clus=rootVert)
crv <- getCurves(lin)
plot(rd, col =  cl ,pch=16, asp = 1)
lines(crv, lwd=3)
legend("topright",
       legend=1:length(unique(cl)),
       fill=c(1:length(unique(cl))),
       pch=15,
       title = 'Vertex')
pt_s <- pseudotime(crv)
```


```{r de, echo=FALSE} 
pt_p = pt_s[,1]
heatdata1 <- expr[, order(pt_p, na.last = NA)]
heatclus1 <- cl[order(pt_p, na.last = NA)]
ce1 <- clusterExperiment(heatdata1, heatclus1, transformation=identity)
plotHeatmap(ce1, clusterSamplesData="orderSamplesValue")
```


```{r lineageTest, echo=FALSE}
slingPaths = ptSling.to.ptLin(pt_s)
lp <- testPath(slingPaths[[1]], expr)

```

```{r lineageTest, echo=FALSE}
lsObjLP <- testProjectionLineages(p, root)
lsSiGenes <- testSigGenes(lsObjLP)
uGenes <- unique(unlist(lsSiGenes))
```
