#' Wrapper for the output from a FastProject object. Generated by calling Analyze on a defined
#' FastProject object.

setMethod("initialize", signature(.Object="FastProjectOutput"), 
          function(.Object, eData, projDataList) {
            
            .Object@exprData <- eData
            .Object@projData <- projDataList
            
            return(.Object)
          }
)