#' Wrapper for the output from a FastProject object. Generated by calling Analyze on a defined
#' FastProject object.

setMethod("initialize", signature(.Object="FastProjectOutput"), 
          function(.Object, eData, projDataList, sigScores, randomSigScores, weights) {
            
            .Object@exprData <- eData
            .Object@projData <- projDataList
            .Object@sigScores <- sigScores
            .Object@randomSigScores <- randomSigScores
            .Object@weights <- weights
            
            return(.Object)
          }
)

