#' Wrapper for the output from a FastProject object. Generated by calling Analyze on a defined
#' FastProject object.

library(jug)
library(jsonlite)

setMethod("initialize", signature(.Object="FastProjectOutput"), 
          function(.Object, eData, projDataList, sigMatrix, randomSigScores, weights, sigList) {
            
            .Object@exprData <- eData
            .Object@projData <- projDataList
            .Object@sigMatrix <- sigMatrix
            .Object@randomSigScores <- randomSigScores
            .Object@weights <- weights
            .Object@sigList <- sigList
            
            return(.Object)
          }
)

setMethod("saveFPOutAndViewResults", signature(fpout="FastProjectOutput"),
          function(fpout) {
            #' Generate an HTML Output Report from a FastProjectOutput Object by first saving the object
            #' Includes a server script for getting json data from FastProjectOutput
            #' 
            #' Parameters:
            #'  object: FastProjectOutput object
            #'    Data object obtained from running Analyze() on a FastProject object
            #'  url: character
            #'    URL to generate output report at
            
            i <- 1
            ofile <- paste0("FastProject_Output/fpout", i, ".rds")
            while (file.exists(ofile)) {
              i <- i+1
              ofile <- paste0("FastProject_Output/fpout", i, ".rds")
            }
              
            saveRDS(fpout, file=ofile)
            arg1 <<- ofile
            
            message("Launching the server...")
            message("Press exit or ctrl c to exit")
            source("FastProject_Output/server_script.R")
})

setMethod("viewResults", signature(fpout="FastProjectOutput"), 
          function(fpout) {
            
            arg1 <<- fpout
            message("Launching the server...")
            message("Press exit or ctrl c to exit")
            source("FastProject_Output/server_script.R")
})