# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geary <- function(X, W) {
    .Call('_VISION_geary', PACKAGE = 'VISION', X, W)
}

geary_sparse <- function(X, ind, W) {
    .Call('_VISION_geary_sparse', PACKAGE = 'VISION', X, ind, W)
}

geary_sparse_local <- function(X, ind, W) {
    .Call('_VISION_geary_sparse_local', PACKAGE = 'VISION', X, ind, W)
}

geary_all <- function(X, W) {
    .Call('_VISION_geary_all', PACKAGE = 'VISION', X, W)
}

geary_sparse_all <- function(X, ind, W) {
    .Call('_VISION_geary_sparse_all', PACKAGE = 'VISION', X, ind, W)
}

point_mult <- function(X, Y) {
    invisible(.Call('_VISION_point_mult', PACKAGE = 'VISION', X, Y))
}

multMat <- function(X, Y) {
    .Call('_VISION_multMat', PACKAGE = 'VISION', X, Y)
}

sigGeneInner <- function(sigScores, exp, geneIndices) {
    .Call('_VISION_sigGeneInner', PACKAGE = 'VISION', sigScores, exp, geneIndices)
}

wilcox_subset <- function(vals, indicesA, indicesB) {
    .Call('_VISION_wilcox_subset', PACKAGE = 'VISION', vals, indicesA, indicesB)
}

